all_users/api/urls.py
# all_users urls.py

from django.urls import path
from .views import (
					UserCreateAPIView,
					UserDetailAPIView,
					UserListAdminAPIView,
					UserRetrieveAdminAPIView,
					)

app_name = 'user-api'

urlpatterns =  [
	path('create/', UserCreateAPIView.as_view(), name='create'),
	path('<int:pk>', UserDetailAPIView.as_view(), name='detail'),
	path('admin-list/', UserListAdminAPIView.as_view(), name='admin-list'),
	path('admin-detail/<int:pk>', UserRetrieveAdminAPIView.as_view(), name='admin-detail'),
]

all_users/urls.py
# all_users urls.py

from django.urls import path
from .views import SignUpView, login_view

app_name = 'all_users'

urlpatterns = [
	path('signup/', SignUpView.as_view(), name='signup'),
	path('login/', login_view, name='login'),
]

candidates/api/urls.py
# candidate/api urls.py

from django.urls import path

from .views import (
	CandidateListAPIView,
	CandidateCreateAPIView,
	CandidateDetailView,
	)


app_name = 'candidate-api'

urlpatterns = [
	path('', CandidateListAPIView.as_view(), name='list'),
	path('create/', CandidateCreateAPIView.as_view(), name='create'),
	path('<int:pk>/', CandidateDetailView.as_view(), name='detail'),
]

jobsite/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('user/', include('all_users.urls', namespace='all_users')),

    path('api/user/', include('all_users.api.urls', namespace='user-api')),
    path('api/candidate/', include('candidates.api.urls', namespace='candidate-api')),
    
]

all_users/models.py
# all_users models.py

from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

	CANDIDATE = 'candidate'
	EMPLOYER = 'employer'

	user_type_choices = (
		(CANDIDATE, 'Candidate'),
		(EMPLOYER, 'Employer'),
	)

	user_type = models.CharField(
		max_length = 50,
		choices = user_type_choices,
		default = CANDIDATE,
	)

	@property
	def is_candidate(self):
		if self.user_type == 'candidate':
			return True
		return False

	@property
	def is_employer(self):
		if self.user_type == 'employer':
			return True
		return False
	
	

candidates/models.py
# candidates models.py

from django.db import models
from django.urls import reverse

from all_users.models import User

class CandidateProfile(models.Model):

	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	biography = models.TextField()
	LinkedIn = models.URLField(blank=True)
	website = models.URLField(blank=True)

	def __str__(self):
		return self.user.username

	def get_absolute_url(self):
		return reverse('candidate-api:reverse')

all_users/api/views.py
# all_users/api views.py

from rest_framework import generics
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework import status

from django.contrib.auth import get_user_model
from .serializers import UserDisplaySerializer, UserCreationSerializer
from .permissions import IsOwner

User = get_user_model()

class UserCreateAPIView(generics.CreateAPIView):

	serializer_class = UserCreationSerializer
	permission_classes = [permissions.AllowAny,]

	def post(self, request):

		serializer = UserCreationSerializer(data=request.data)

		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserDetailAPIView(generics.RetrieveUpdateAPIView):

	serializer_class = UserCreationSerializer
	permission_classes = [permissions.IsAuthenticated, IsOwner]

	def get_queryset(self, *args, **kwargs):
		return User.objects.all()

class UserListAdminAPIView(generics.ListAPIView):

	serializer_class = UserDisplaySerializer
	permission_classes = [permissions.IsAdminUser,]

	def get_queryset(self, *args, **kwargs):
		return User.objects.all()

class UserRetrieveAdminAPIView(generics.RetrieveAPIView):

	serializer_class = UserDisplaySerializer
	permission_classes = [permissions.IsAdminUser,]

	def get_queryset(self, *args, **kwargs):
		return User.objects.all()



# detail view retrieve, update
# list view for admin

all_users/views.py
# all_users views.py

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from django.views.generic import TemplateView
from django.http import HttpResponse

import json

class SignUpView(TemplateView):

	template_name = 'all_users/signup.html'


def login_view(request):

	if request.method == 'POST':

		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)

		response_data = {}

		if user is not None:
			login(request, user)
			response_data['result'] = 'success'
		elif username == '' or password == '':
			response_data['result'] = 'failed'
			response_data['message'] = 'Username or password cannot be blank'
		else:
			response_data['result'] = 'failed'
			response_data['message'] = 'Username or password incorrect'

	return HttpResponse(
		json.dumps(response_data),
		content_type='application/json',
		status=201)

candidates/api/views.py
# candidates/api views.py

from rest_framework import generics
from rest_framework import permissions

from candidates.models import CandidateProfile
from .serializers import CandidateProfileSerializer
from all_users.api.permissions import IsCandidate, IsOwnerOrReadOnly

class CandidateListAPIView(generics.ListAPIView):

	serializer_class = CandidateProfileSerializer

	def get_queryset(self, *args, **kwargs):
		return CandidateProfile.objects.all()

class CandidateCreateAPIView(generics.CreateAPIView):

	serializer_class = CandidateProfileSerializer
	permission_classes = [permissions.IsAuthenticated, IsCandidate,]

	def perform_create(self, serializer):
		serializer.save(user=self.request.user)

class CandidateDetailView(generics.RetrieveUpdateAPIView):

	serializer_class = CandidateProfileSerializer
	permission_classes = [permissions.IsAuthenticated, IsOwnerOrReadOnly]

	def get_queryset(self, *args, **kwargs):
		return CandidateProfile.objects.all()

# class CandidateUpdateAPIView(generics.UpdateAPIView):

# 	serializer_class = CandidateProfileSerializer
# 	permissions_classes = [permissions.IsAuthenticated, IsOwner,]

# 	def get_queryset(self, *args, **kwargs):
# 		return CandidateProfile.objects.all()

candidates/views.py
from django.shortcuts import render

# Create your views here.

jobsite/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

class HomeView(TemplateView):
	template_name = 'home.html'

all_users/templates/all_users/signup.html
{% extends "base.html" %}
{% load static %}

{% block link %}
	<link rel="stylesheet" type="text/css" href="{% static 'all_users/all_users.css' %}">
{% endblock link %}

{% block content %}

	<div id="csrf_token">
		{% csrf_token %}
	</div>

	<div class="container">

		<div class="row">
			<div class="col-sm-5">
				<h4>Sign up</h4>
				<form>
					<div class="signUpError" id="signUpNonFieldError"></div>
					<div class="form-group">
						<label for="signUpUsername">Username</label>
						<div class="signUpError" id="signUpUsernameError"></div>
						<input type="text" class="form-control" id="signUpUsername" placeholder="Enter username">
					</div>
					<div class="form-group">
						<label for="signUpEmail">Email</label>
						<div class="signUpError" id="signUpEmailError"></div>
						<input type="email" class="form-control" id="signUpEmail" placeholder="Enter email">
					</div>
					<div class="form-group">
						<label for="signUpUserType">User Type</label>
						<select class="form-control" id="signUpUserType">
							<option>candidate</option>
							<option>employer</option>
						</select>
					</div>
					<div class="form-group">
						<label for="signUpPassword">Password</label>
						<div class="signUpError" id="signUpPasswordError"></div>
						<input type="password" class="form-control" id="signUpPassword1" placeholder="Password">
					</div>
					<div class="form-group">
						<label for="signUpPassword">Confirm Password</label>
						<div class="signUpError" id="signUpConfirmPasswordError"></div>
						<input type="password" class="form-control" id="signUpPassword2" placeholder="Password">
					</div>
					<button type="submit" class="btn btn-primary" id="signUpButton">Sign up</button>
				</form>
			</div>
			<div class="col-sm-2"></div>
			<div class="col-sm-5">
				<h4>Login</h4>
				<form>
					<div class="loginError"></div>
					<div class="form-group">
						<label for="loginUsername">Username</label>
						<input type="text" class="form-control" id="loginUsername" placeholder="Enter username">
					</div>
					<div class="form-group">
						<label for="loginPassword1">Password</label>
						<input type="password" class="form-control" id="loginPassword" placeholder="Password">
					</div>
					<button type="submit" class="btn btn-primary" id="loginButton">Login</button>
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

{% block script %}

	<script type="text/javascript" src="{% static 'all_users/signup.js' %}"></script>

{% endblock script %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>

	<title></title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	{% block link %}
		
	{% endblock link %}
</head>
<body>

	{% include "navbar.html" %}

	{% block content %}
		
	{% endblock content %}



	<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	
	{% block script %}
	{% endblock script %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

<div class="container">
	<h1>Welcome!</h1>
</div>



	
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#">Features</a>
            <a class="nav-item nav-link" href="{% url 'all_users:signup' %}">Sign up/Login</a>
            
        </div>
    </div>
</nav>